#!/bin/bash

# Pull the git commit message
commit_message=$(git log --pretty="format: %s" -1 $newrev)

#figure out whether or not to skip ci, we don't allow it on integration or master
skip_ci="false"

if [[ "$commit_message" =~ \-\-skip-ci ]]
then
  if [[ ! "$TARGET_BRANCH" =~ ^integration\/* ]] && [[ ! "$TARGET_BRANCH" =~ ^master\/* ]]
  then
    skip_ci="true"
  else
    skip_ci="false"
    echo "--skip-ci ignored for integration and master branches"
  fi
fi

# Firing off the build
if [ $skip_ci == "true" ]
then
  echo "--skip-ci passed, CI build not triggered for $TARGET_BRANCH"
else
  # we don't want to trigger a build on pushing up branch tags
  if [[ "$TARGET_BRANCH" =~ ^refs\/tags\/* ]]
  then
    echo "CI build not triggered for $TARGET_BRANCH"
  else
    curl -G --data-urlencode "token=$JENKINS_BUILD_TOKEN" --data-urlencode "BRANCH=$TARGET_BRANCH" --data-urlencode "LAST_COMMITTER=$LAST_COMMITTER" "http://$JENKINS_USERNAME:$JENKINS_PASSWORD@$JENKINS_SERVER/job/$JENKINS_JOB_NAME/buildWithParameters"
    echo "Triggered CI build for $TARGET_BRANCH with the last committer being $LAST_COMMITTER"
  fi
fi
